# Generated by Django 5.0.6 on 2024-05-25 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_code', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=500, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='media/unknown_user.png', null=True, upload_to='Profile_Pics')),
                ('parent_referral', models.CharField(blank=True, max_length=1000, null=True)),
                ('pool', models.IntegerField(blank=True, default=0, null=True)),
                ('device_token', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('main_wallet', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('referral_wallet', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('terms_privacy', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
