# Generated by Django 5.0.6 on 2024-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('otpcount', models.IntegerField(default=0)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
