# Generated by Django 5.0.6 on 2024-05-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0003_lottery_lotteryticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lottery', to='mygame.lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to='mygame.userprofile')),
            ],
        ),
    ]
