# Generated by Django 5.0.6 on 2024-05-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0005_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='lottery_code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lottery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lottery', to='mygame.lottery'),
        ),
    ]
