# Generated by Django 5.0.6 on 2024-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0006_transaction_lottery_code_alter_transaction_lottery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='admin_email'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
    ]
