# Generated by Django 5.0.6 on 2024-06-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0007_alter_adminprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='lottery_time',
            field=models.CharField(default=3, max_length=200),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('resolve', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_support', to='mygame.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
