# Generated by Django 5.0.6 on 2024-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0008_lottery_lottery_time_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='lottery_price',
            field=models.CharField(default=10, max_length=200),
        ),
    ]
