# Generated by Django 5.0.6 on 2024-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0010_gamedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='comp_revenue',
            field=models.CharField(default=10, max_length=200),
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='referal_per',
            field=models.CharField(default=10, max_length=200),
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='user_revenue',
            field=models.CharField(default=90, max_length=200),
        ),
    ]
