# Generated by Django 5.0.6 on 2024-06-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0011_gamedetails_comp_revenue_gamedetails_referal_per_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_bet', models.CharField(blank=True, max_length=2000, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('game_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_transaction', to='mygame.adminprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
