# Generated by Django 5.0.6 on 2024-06-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0012_lotteryhistory_admintransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pool',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='refer_code',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
